### ISSUE TITLE
OpinionDetails: Löschvormerkung über Berechtigung "Edit" berücksichtigen

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#13]
Momentan kann ein OpinionDetail nicht zum Löschen markiert werden bei Berechtigung "Edit".
Fehlermeldung:
Es ist ein interner Fehler aufgetreten. [Keine Berechtigung zum Löschen dieses Details zum Gutachten.]

**Comment by rene-mebedo** [comment]
Getestet. Funktioniert jetzt!
