### ISSUE TITLE
PDF Vorschau

### ISSUE THREAD

**Issue by rene-mebedo** [rene-mebedo/edelrahmmandel#18]
Realisieren einer PDF Vorschau, damit nicht 1000 PDF Versionen abgelegt werden. Die Vorschau sollte lediglich temporär sein und nicht dauerhaft auf dem Server gespeichert werden.

**Comment by Marc-MEBEDO** [comment]
Alternativ oder auch zusätzlich die Möglichkeit implementieren, bereits erzeugte PDFs zu löschen
