### ISSUE TITLE
Kapitelnummerierung der Fragen nicht korrekt bei Übergabe an opinion-documenter

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#20]
Seit deinen Änderungen am 5.2. (vermute ich), stimmt unter Umständen in der Übergabe an opinion-documenter die Kapitelnummerierung der Fragen nicht mehr.
Ich habe mir die entsprechenden JSON Objekte angeschaut und mir ist aufgefallen, dass in in einem solchen Fall parentPosition und printParentPosition voneinander abweichen.
Dabei ist der Inhalt von printParentPosition  korrekt und von parentPosition nicht.
Im übergebenen htmlContent setzt sich der Wert dann aus parentPosition und position zusammen.

**Comment by rene-mebedo** [comment]
getestet. Ist nun i.O. mit update auf opinion-doumenter 1.0.27
