### ISSUE TITLE
Neues Gutachten auf Basis einer Vorlage: ids im htmlContent sind falsch

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#23]
In einem neuen Gutachten, bei dem eine Vorlage ausgewählt wurde, funktionieren die Links (a href...) nicht für die aus der Vorlage übernommenen OpinionDetails.
Bei diesen OpinionDetails ist im htmlContent bei "div id=..." die ID aus der Vorlage angegeben und nicht die (richtige) aus dem neuen Gutachten.

**Comment by rene-mebedo** [comment]
Ich habe den Bug gefunden. Ich glaube es ist am besten vor jedem Aufruf des createPDF ein reRender der Templates zu machen.
