### ISSUE TITLE
Bildbearbeitung im Nachgang

### ISSUE THREAD

**Issue by rene-mebedo** [rene-mebedo/edelrahmmandel#25]
Markierungsmöglichkeit implementieren

**Comment by Marc-MEBEDO** [comment]
To-Dos bzgl. Markierung:
**Bitte dazu mit mir Rücksprache halten** :-)

1. Markiertes Bild darstellen/laden inkl. (gespeichertem) State
u: .\imports\ui\ListImages.jsx
u: .\imports\ui\components\ImageAnnotation.jsx
u: .\server\methods\images.js

2. Markiertes Bild an PDF übergeben
=> u: .\imports\api\constData\layouttypes.js
n(ew): .\imports\api\helpers\image.js

3. "Feinschliff Layout" markerjs: Zur Verfügung stehende Marker, Defaulteinstellungen (UI-Colors nicht!)
=> u: .\imports\ui\components\ImageAnnotation.jsx => showMarkerArea()

**Comment by Marc-MEBEDO** [comment]
Neueste Version von opinion-documenter ist zu verwenden wegen der Verarbeitung der übergebenen, markierten Bilder.
Version 1.0.29

**Comment by rene-mebedo** [comment]
markerjs implementiert
