### ISSUE TITLE
Sortierung Aufstellung Maßnahmen

### ISSUE THREAD

**Issue by rene-mebedo** [rene-mebedo/edelrahmmandel#48]
Nicht alphanumerisch sondern nach Kapitel und depth

**Comment by Marc-MEBEDO** [comment]
Sortierung der actionListitems numerisch.
Das (=Sortierung des Arrays) ist notwendig, weil leider Funktionalität Mongo collation nicht enthalten ist unter Meteor.
Mit collation wäre nur folgendes notwendig in collection.find():
_collation: {
        locale: 'de',
        numericOrdering: true
}_
Siehe auch https://forums.meteor.com/t/is-there-a-way-to-use-mongodb-3-4-collation/33024/13

**Comment by Marc-MEBEDO** [comment]
Umsetzung (richtige Sortierung) funktioniert nicht, wenn Frage auf erster Ebene liegt, als ganz ohne mindestens einenn vorgeschalteten (Heading) Baustein.
Das können wir jedoch aus meiner Sicht ignorieren, da es in der Praxis nicht vorkommen sollte, dass Fragen auf erster Ebene vorkommen in einem Assessment/Gutachten.
