### ISSUE TITLE
Bearbeitung von OpinionDetails: Icons für die Formatierung fehlen

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#5]
Siehe markierten Teil im Screenshot:
![grafik](https://user-images.githubusercontent.com/73165179/106281423-7debd000-623f-11eb-850e-ea82f8f9a335.png)

**Comment by rene-mebedo** [comment]
Das hatte ich bei mir auch schon mal. jedoch kann ich es nicht reproduzieren. Kannst Du es reproduzieren?

**Comment by rene-mebedo** [comment]
Aktuell nicht mehr nachvollziehbar... close
![image](https://user-images.githubusercontent.com/72870284/106453561-cc8caa80-6489-11eb-96a3-889a6006b492.png)

**Comment by rene-mebedo** [comment]
Es liegt am Ladeverhalten im Produktivsystem, wenn man nicht aus dem Root-Verzeichnis die Anwendung lädt.

**Comment by rene-mebedo** [comment]
funktioniert nun nach der Umstellung siehe auch [https://github.com/meteor/meteor/issues/10247](https://github.com/meteor/meteor/issues/10247)
