### ISSUE TITLE
Möglichkeit, zusätzliche Maßnahmen aufzunehmen, die nicht aus der Befragung kommen

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#60]
Info von BE:
In der Aufstellung der Maßnahmen wurden bisher (in Word) weitere Maßnahmen/Handlungsempfehlungen manuell eingefügt, die bei der Begehung aufgefallen sind und für die es keine konkrete Frage in der Befragung gibt.
Diese Funktion wäre ebenfalls sinnvoll.

**Comment by rene-mebedo** [comment]
Am Folgetermin der GutachtenApp wurde dieser Punkt besprochen und gezeigt wie man durch einen eigenständigen Punkt und einer Frage/Antwort ind. Maßnahmen erfassen kann, die beim Betriebsrundgang aufgefallen sind.
