### ISSUE TITLE
(Scheinbare) Probleme beim Hochladen "größerer" Bilder

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#61]
Von BE:
1. Werden im Bildcontainer Bilder > 1 MB hochgeladen, so erscheint eine Fehlermeldung:
![grafik](https://user-images.githubusercontent.com/73165179/137686829-490af80c-0107-4592-adcc-a466639a5db4.png)
Die Bilder sind trotzdem im Bildcontainer enthalten.

2. Das Löschen des Bildes im Hochladefenster (im Sceenshot über Mülltonne) ist nicht möglich.

**Comment by rene-mebedo** [comment]
`client_max_body_size 100M;` in `/etc/nginx/nginx.conf` hinzugefügt. funktioniert nun ohne warning.

siehe auch:
[https://medium.com/@svsh227/error-413-request-entity-too-large-in-nginx-with-client-max-body-size-changes-in-nginx-6aacd525fe11](https://medium.com/@svsh227/error-413-request-entity-too-large-in-nginx-with-client-max-body-size-changes-in-nginx-6aacd525fe11)
