### ISSUE TITLE
Inhaltliche Punkte

### ISSUE THREAD

**Issue by rene-mebedo** [rene-mebedo/edelrahmmandel#64]
1. Es muss ein fachliche Verantwortung definiert werden
2. Entscheiderkreis festgelegt, die bei Änderungen gefragt/informiert werden

3. Copyright auf Bildern - wollen wir das - wurde teilweise bemängelt in der Schulung
4. Punkt 8 fachliche Handlungsempfehlung kann entfallen???

**Comment by Marc-MEBEDO** [comment]
Ist geklärt worden:
1. MaS und OS
2. Läuft über 1.
3. Durch Option in opinion einstellbar
4. Inhalte durch 1. geklärt
