### ISSUE TITLE
Inhaltliche Punkte

### ISSUE THREAD

**Issue by rene-mebedo** [rene-mebedo/edelrahmmandel#69]
folgende Auffälligkeiten in der Vorlage Gutachten (gemeldet von BE):

Frage 4.4.4 
Ja vorhanden -> Es besteht Handlungsbedarf
Nein, nicht vorhanden -> kein Handlungsbedarf
Sollte eher umgekehrt sein

Frage 4.4.7
2. Antwort
notwendig/nicht notwendig in derselben Antwort?

4.5.3
Antworten umfassen nicht alle Möglichkeiten, könnte um folgende ergänzt werden.
Vorhanden, aber nicht richtig benannt.

4.7.5
Antwort: Nicht vorhanden
Sollte ergänzt werden

4.11.1
Nur eine Antwortmöglichkeit

4.18.1
Antwort: Aktuell
Schreibfehler Anlagen

4.19.11
Ja vorhanden -> Es besteht dringender Handlungsbedarf
Nein, nicht vorhanden -> kein Handlungsbedarf
Sollte eher umgekehrt sein

4.20.3
Antwort Nein
befähigenden ->befähigten

4.32.3
Antwort: Entfällt
Sollte ergänzt werden

=============================

4.1.2 
Antwort „NICHT vorhanden“
Den Sachverständigen, da immer 2 vor Ort sind

4.3.1
Antwort „NICHT vorhanden“
Die Antwort ist eine Handlungsempfehlung

4.3.5
Hinweis befüllen

4.6.2
Antwort „nicht vorhanden“
MS-Bereich gibt es nicht mehr.
Handlungsbedarf sollte standardmäßig auf Handlungsbedarf stehen.

4.6.5
Negative Antwort fehlt

4.7.1
Negative Antwort fehlt

Bei Teilweise Grammatik anpassen

4.7.2
Antwort „nicht genau bekannt“
Handlungsempfehlung sollte sich nur auf den Notfall beziehen. VON EFK oder EuP begleitet werden.

4.8.1
Antwortmöglichkeiten erweitern

4.9
Antwortmöglichkeiten erweitern

4.9.1
Antwort gehört teilweise zu 4.9.2

4.10.1
JA, nicht aktuell?

4.12.1
Teilweise hinzufügen

4.13.3
Antwort „NEIN“
Grammatik

4.13.4
Antworten

4.15.1
Antwort „nicht notwendig“ einfügen

4.17.2
Keine antworten

**Comment by Marc-MEBEDO** [comment]
Diese (und ggf. auch weitere) Punkte sind in der internen Klärung

**Comment by Marc-MEBEDO** [comment]
Ist per E-Mail geklärt und abgeschlossen worden

**Comment by Marc-MEBEDO** [comment]
.
