### ISSUE TITLE
Antwort als zutreffend auswählen kann nicht rückgängig gemacht werden

### ISSUE THREAD

**Issue by Marc-MEBEDO** [rene-mebedo/edelrahmmandel#7]
Wird eine Antwort als zutreffend ausgewählt, kann ich dies nicht mehr rückgängig machen in den Aktivitäten.
Es werden in der entsprechenden Aktivität über details zwar die Änderungen angezeigt. Die Funktion "Änderung rückgängig machen" führt jedoch zur Meldung "Es wurden keine Änderungen durchgeführt...".
Siehe Screenshots:
![grafik](https://user-images.githubusercontent.com/73165179/106282894-8218ed00-6241-11eb-95ea-1c0be9efcd0c.png)
![grafik](https://user-images.githubusercontent.com/73165179/106282920-893ffb00-6241-11eb-9bbe-fdfc1bb1b7e9.png)

**Comment by rene-mebedo** [comment]
Das Rückgängig machen wird rausgenommen, da die Änderungen mehrstufig sind.
